FROM ghcr.io/rwkv/rwkv-infctx-trainer:env-cuda-11-8

# RUN mkdir /tmp/bore && cd /tmp/bore && \
#     apt-get update && apt-get install -y curl && \
#     $(curl https://sh.rustup.rs -sSf | bash -s -- -y) && \
#     ~/.cargo/env && cargo install bore-cli
